plugins {
    id 'org.relativitymc.neo-loom'
    id 'java-library'
    id 'maven-publish'
}
group = project.mod_group
version = project.mod_version
base { archivesName = "${project.mod_id}-${project.name}" }
java.toolchain.languageVersion = JavaLanguageVersion.of(project.java_version)
repositories {
    maven { url = 'https://maven.blamejared.com' }
}
dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
}
jar { from(rootProject.file('LICENSE')) }
processResources {
    def p = [mod_id:mod_id, mod_group:mod_group, mod_version:mod_version, mod_name:mod_name,
        mod_description:mod_description, mod_author:mod_author, mod_homepage:mod_homepage,
        mod_github:mod_github, mod_license:mod_license, mod_icon:mod_icon, java_version:java_version,
        minecraft_version:minecraft_version, minecraft_version_range:minecraft_version_range,
        fabric_loader_version:fabric_loader_version, fabric_api_version:fabric_api_version,
        forge_artifact_version:forge_artifact_version, forge_version:forge_version, forge_version_range:forge_version_range, neoforge_version:neoforge_version,
        common_network_version:common_network_version]
    def json = p.collectEntries { k,v -> [(k): v instanceof String ? v.replace('\n','\\\\n') : v] }
    filesMatching(['META-INF/mods.toml','META-INF/neoforge.mods.toml']) { expand p }
    filesMatching(['fabric.mod.json','pack.mcmeta']) { expand json }
    inputs.properties p
}
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
